### PR TITLE
Removed superfluous access modifiers to silence Swift 5 warnings

### PR DESCRIPTION
**Pull request by tcldr**
Eliminates warnings when building with Xcode 10.2b2

### CODE REVIEW

**Comment by devxoul** [comment]
Can I access those variables without `public` modifier in Swift 4?

**Comment by tcldr** [comment]
From the docs: “you can mark an extension with an explicit access level modifier (for example, private extension) to set a new default access level for all members defined within the extension. This new default can still be overridden within the extension for individual type members.”

This is the case even for Swift 4.

The difference in Swift 5 is that you now get a warning if you set a property access modifier that is the same as the default access level already set by the enclosing scope.

**Comment by devxoul** [comment]
Thanks for your contribution!

**Comment by tcldr** [comment]
Pleasure! Happy to help. Thanks for a great library.

**Pull request merged**
